package view;

import com.placeholder.PlaceHolder;
import model.Fasores;
import model.FlagSyntax;
/**
 *
 * @author Franco
 */
public class FasoresGUI extends javax.swing.JFrame {

    /**
     * Creates new form fasores
     */
    public FasoresGUI() {
        initComponents();
        setPlaceholders();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSideMenu = new javax.swing.JPanel();
        jPanelAppTitle = new javax.swing.JPanel();
        appTitle = new java.awt.Label();
        jPanelAppTitle1 = new javax.swing.JPanel();
        jButtonVolver = new javax.swing.JButton();
        jButtonOpBasicas = new javax.swing.JButton();
        jButtonOpAvanzadas = new javax.swing.JButton();
        jButtonFasores = new javax.swing.JButton();
        jLabelResultado = new javax.swing.JLabel();
        jTextFieldFasorFAmp = new javax.swing.JTextField();
        jTextFieldFasorGAmp = new javax.swing.JTextField();
        jButtonSumaFasores = new javax.swing.JButton();
        jTextFieldFasorFDesp = new javax.swing.JTextField();
        jTextFieldFasorGFase = new javax.swing.JTextField();
        jTextFieldFasorGDesp = new javax.swing.JTextField();
        jTextFieldFasorFFase = new javax.swing.JTextField();
        jComboBoxF = new javax.swing.JComboBox<>();
        jComboBoxG = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelG = new javax.swing.JLabel();
        jLabelF = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sumatoria de Fasores");
        setResizable(false);

        jPanelSideMenu.setBackground(new java.awt.Color(25, 33, 43));
        jPanelSideMenu.setToolTipText("");

        jPanelAppTitle.setBackground(new java.awt.Color(38, 47, 61));
        jPanelAppTitle.setToolTipText("");

        appTitle.setAlignment(java.awt.Label.CENTER);
        appTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        appTitle.setForeground(new java.awt.Color(225, 232, 240));
        appTitle.setText("NCOM APP");

        javax.swing.GroupLayout jPanelAppTitleLayout = new javax.swing.GroupLayout(jPanelAppTitle);
        jPanelAppTitle.setLayout(jPanelAppTitleLayout);
        jPanelAppTitleLayout.setHorizontalGroup(
            jPanelAppTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(appTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelAppTitleLayout.setVerticalGroup(
            jPanelAppTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAppTitleLayout.createSequentialGroup()
                .addComponent(appTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelAppTitle1.setBackground(new java.awt.Color(38, 47, 61));
        jPanelAppTitle1.setToolTipText("");

        jButtonVolver.setBackground(new java.awt.Color(38, 47, 61));
        jButtonVolver.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonVolver.setForeground(new java.awt.Color(225, 232, 240));
        jButtonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/Back Icon.png"))); // NOI18N
        jButtonVolver.setText("Volver");
        jButtonVolver.setBorder(null);
        jButtonVolver.setBorderPainted(false);
        jButtonVolver.setContentAreaFilled(false);
        jButtonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAppTitle1Layout = new javax.swing.GroupLayout(jPanelAppTitle1);
        jPanelAppTitle1.setLayout(jPanelAppTitle1Layout);
        jPanelAppTitle1Layout.setHorizontalGroup(
            jPanelAppTitle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAppTitle1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelAppTitle1Layout.setVerticalGroup(
            jPanelAppTitle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAppTitle1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonOpBasicas.setBackground(new java.awt.Color(25, 33, 43));
        jButtonOpBasicas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonOpBasicas.setForeground(new java.awt.Color(225, 232, 240));
        jButtonOpBasicas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/Plus Icon.png"))); // NOI18N
        jButtonOpBasicas.setText("   Operaciones Básicas");
        jButtonOpBasicas.setBorder(null);
        jButtonOpBasicas.setBorderPainted(false);
        jButtonOpBasicas.setContentAreaFilled(false);
        jButtonOpBasicas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonOpBasicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpBasicasActionPerformed(evt);
            }
        });

        jButtonOpAvanzadas.setBackground(new java.awt.Color(25, 33, 43));
        jButtonOpAvanzadas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonOpAvanzadas.setForeground(new java.awt.Color(225, 232, 240));
        jButtonOpAvanzadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/Square Root Icon.png"))); // NOI18N
        jButtonOpAvanzadas.setText(" Operaciones Avanzadas");
        jButtonOpAvanzadas.setBorder(null);
        jButtonOpAvanzadas.setBorderPainted(false);
        jButtonOpAvanzadas.setContentAreaFilled(false);
        jButtonOpAvanzadas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonOpAvanzadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpAvanzadasActionPerformed(evt);
            }
        });

        jButtonFasores.setBackground(new java.awt.Color(25, 33, 43));
        jButtonFasores.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonFasores.setForeground(new java.awt.Color(225, 232, 240));
        jButtonFasores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/Fasores Icon.png"))); // NOI18N
        jButtonFasores.setText("   Sumatoria de Fasores");
        jButtonFasores.setBorder(null);
        jButtonFasores.setBorderPainted(false);
        jButtonFasores.setContentAreaFilled(false);
        jButtonFasores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonFasores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFasoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSideMenuLayout = new javax.swing.GroupLayout(jPanelSideMenu);
        jPanelSideMenu.setLayout(jPanelSideMenuLayout);
        jPanelSideMenuLayout.setHorizontalGroup(
            jPanelSideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAppTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelAppTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSideMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelSideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonOpAvanzadas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonFasores))
                .addContainerGap())
            .addGroup(jPanelSideMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonOpBasicas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSideMenuLayout.setVerticalGroup(
            jPanelSideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSideMenuLayout.createSequentialGroup()
                .addComponent(jPanelAppTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButtonOpBasicas)
                .addGap(18, 18, 18)
                .addComponent(jButtonOpAvanzadas)
                .addGap(18, 18, 18)
                .addComponent(jButtonFasores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 289, Short.MAX_VALUE)
                .addComponent(jPanelAppTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabelResultado.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextFieldFasorFAmp.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldFasorFAmp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldFasorFAmp.setToolTipText("");
        jTextFieldFasorFAmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFasorFAmpActionPerformed(evt);
            }
        });

        jTextFieldFasorGAmp.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldFasorGAmp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldFasorGAmp.setToolTipText("");
        jTextFieldFasorGAmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFasorGAmpActionPerformed(evt);
            }
        });

        jButtonSumaFasores.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonSumaFasores.setText("SUMAR");
        jButtonSumaFasores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSumaFasoresActionPerformed(evt);
            }
        });

        jTextFieldFasorFDesp.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldFasorFDesp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldFasorFDesp.setToolTipText("");
        jTextFieldFasorFDesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFasorFDespActionPerformed(evt);
            }
        });

        jTextFieldFasorGFase.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldFasorGFase.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldFasorGFase.setToolTipText("");
        jTextFieldFasorGFase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFasorGFaseActionPerformed(evt);
            }
        });

        jTextFieldFasorGDesp.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldFasorGDesp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldFasorGDesp.setToolTipText("");
        jTextFieldFasorGDesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFasorGDespActionPerformed(evt);
            }
        });

        jTextFieldFasorFFase.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldFasorFFase.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldFasorFFase.setToolTipText("");
        jTextFieldFasorFFase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFasorFFaseActionPerformed(evt);
            }
        });

        jComboBoxF.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jComboBoxF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cos", "Sen" }));
        jComboBoxF.setToolTipText("");
        jComboBoxF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFActionPerformed(evt);
            }
        });

        jComboBoxG.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jComboBoxG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cos", "Sen" }));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Funcion g(t)");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Funcion f(t)");
        jLabel2.setToolTipText("");

        jLabelG.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelG.setToolTipText("");

        jLabelF.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelF.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelSideMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelF, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelG, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxF, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addComponent(jComboBoxG, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldFasorFDesp, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                    .addComponent(jTextFieldFasorFAmp)
                                    .addComponent(jTextFieldFasorFFase))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldFasorGFase, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                    .addComponent(jTextFieldFasorGAmp)
                                    .addComponent(jTextFieldFasorGDesp)))
                            .addComponent(jLabelResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSumaFasores)
                        .addGap(248, 248, 248))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSideMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxF, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxG, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFasorFAmp, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFasorGAmp, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFasorFFase, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFasorGFase, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFasorGDesp, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFasorFDesp, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelG, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jLabelF, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButtonSumaFasores, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setPlaceholders() {
        PlaceHolder holder1 = new PlaceHolder(jTextFieldFasorFAmp, "Ingrese Amplitud de f(t)");
        PlaceHolder holder2 = new PlaceHolder(jTextFieldFasorGAmp, "Ingrese Amplitud de g(t)");
        PlaceHolder holder3 = new PlaceHolder(jTextFieldFasorFFase, "Ingrese Fase de f(t)");
        PlaceHolder holder4 = new PlaceHolder(jTextFieldFasorGFase, "Ingrese Fase de g(t)");
        PlaceHolder holder5 = new PlaceHolder(jTextFieldFasorFDesp, "Ingrese Desplazamiento en f(t)");
        PlaceHolder holder6 = new PlaceHolder(jTextFieldFasorGDesp, "Ingrese Desplazamiento en g(t)");
        holder1.setSize(18);
        holder2.setSize(18);
        holder3.setSize(18);
        holder4.setSize(18);
        holder5.setSize(18);
        holder6.setSize(18);        
    }

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        this.dispose();
        new MainGUI().setVisible(true);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonOpBasicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpBasicasActionPerformed
        this.dispose();
        new OpBasicasGUI().setVisible(true);
    }//GEN-LAST:event_jButtonOpBasicasActionPerformed

    private void jButtonOpAvanzadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpAvanzadasActionPerformed
        this.dispose();
        new OpAvanzadasGUI().setVisible(true);
    }//GEN-LAST:event_jButtonOpAvanzadasActionPerformed

    private void jButtonFasoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFasoresActionPerformed
        this.dispose();
        new FasoresGUI().setVisible(true);
    }//GEN-LAST:event_jButtonFasoresActionPerformed

    private void jTextFieldFasorFAmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFasorFAmpActionPerformed

    }//GEN-LAST:event_jTextFieldFasorFAmpActionPerformed

    private void jTextFieldFasorGAmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFasorGAmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFasorGAmpActionPerformed

    private void jButtonSumaFasoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSumaFasoresActionPerformed
        FlagSyntax flagSyntax = new FlagSyntax();
        Fasores f, g, suma = new Fasores();
        String trig1 = jComboBoxF.getSelectedItem().toString(), trig2 = jComboBoxG.getSelectedItem().toString();
        f = getFasorDeTexto('f', trig1, flagSyntax);
        g = getFasorDeTexto('g', trig2, flagSyntax);
        if (f.fase != g.fase) {
            jLabelResultado.setText("MATH ERROR");
        } else if (flagSyntax.flag != 0) {
            suma = suma.sumarFasores(f, g);
            jLabelResultado.setText(resultadoFasor(suma));
        } else {
            jLabelResultado.setText("SYNTAX ERROR");
        }
    }//GEN-LAST:event_jButtonSumaFasoresActionPerformed

    private void jTextFieldFasorFDespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFasorFDespActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFasorFDespActionPerformed

    private void jTextFieldFasorGFaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFasorGFaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFasorGFaseActionPerformed

    private void jTextFieldFasorGDespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFasorGDespActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFasorGDespActionPerformed

    private void jTextFieldFasorFFaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFasorFFaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFasorFFaseActionPerformed

    private void jComboBoxFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFActionPerformed

    private Fasores getFasorDeTexto(char funcion, String trig, FlagSyntax flagSyntax) {
        Fasores unFasor = new Fasores();
        String amp = "0", desp = "0", fase = "0";
        if (trig.contentEquals("Sen")) {
            unFasor.trig = 's';
        } else {
            unFasor.trig = 'c';
        }
        if (funcion == 'f') {
            try {
                amp = jTextFieldFasorFAmp.getText();
                desp = jTextFieldFasorFDesp.getText();
                fase = jTextFieldFasorFFase.getText();
            } catch (StringIndexOutOfBoundsException e) {
                flagSyntax.flag = 0;
            }
        } else {
            try {
                amp = jTextFieldFasorGAmp.getText();
                desp = jTextFieldFasorGDesp.getText();
                fase = jTextFieldFasorGFase.getText();
            } catch (StringIndexOutOfBoundsException e) {
                flagSyntax.flag = 0;
            }
        }
        try {
            unFasor.amplitud = Double.parseDouble(amp);
            unFasor.desplazamiento = Double.parseDouble(desp);
            unFasor.fase = Double.parseDouble(fase);
            if (funcion == 'f') {
                String f = "f(t) = ";
                if (unFasor.desplazamiento > 0) {
                    desp = "+".concat(desp);
                }
                if (unFasor.desplazamiento == 0) {
                    desp = "";
                }
                f = f.concat(amp).concat(trig).concat("(").concat(fase).concat("t").concat(desp).concat(")");
                jLabelF.setText(f);
            } else {
                String g = "g(t) = ";
                if (unFasor.desplazamiento > 0) {
                    desp = "+".concat(desp);
                }
                if (unFasor.desplazamiento == 0) {
                    desp = "";
                }
                g = g.concat(amp).concat(trig).concat("(").concat(fase).concat("t").concat(desp).concat(")");
                jLabelG.setText(g);
            }
        } catch (NumberFormatException e) {
            flagSyntax.flag = 0;
        }

        return unFasor;
    }

    public String resultadoFasor(Fasores r) {
        String res = "f(t) + g(t) = ", desp = Double.toString(r.desplazamiento), trigo;
        if (r.desplazamiento > 0) {
            desp = "+".concat(desp);
        }
        if (r.desplazamiento == 0) {
            desp = "";
        }
        if (r.trig == 's') {
            trigo = "Sen";
        } else {
            trigo = "Cos";
        }
        res = res.concat(Double.toString(r.amplitud)).concat(trigo).concat("(").concat(Double.toString(r.fase)).concat("t").concat(desp).concat(")");
        return res;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FasoresGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FasoresGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FasoresGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FasoresGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FasoresGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label appTitle;
    private javax.swing.JButton jButtonFasores;
    private javax.swing.JButton jButtonOpAvanzadas;
    private javax.swing.JButton jButtonOpBasicas;
    public javax.swing.JButton jButtonSumaFasores;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxF;
    private javax.swing.JComboBox<String> jComboBoxG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelF;
    private javax.swing.JLabel jLabelG;
    public javax.swing.JLabel jLabelResultado;
    private javax.swing.JPanel jPanelAppTitle;
    private javax.swing.JPanel jPanelAppTitle1;
    private javax.swing.JPanel jPanelSideMenu;
    public javax.swing.JTextField jTextFieldFasorFAmp;
    public javax.swing.JTextField jTextFieldFasorFDesp;
    public javax.swing.JTextField jTextFieldFasorFFase;
    public javax.swing.JTextField jTextFieldFasorGAmp;
    public javax.swing.JTextField jTextFieldFasorGDesp;
    public javax.swing.JTextField jTextFieldFasorGFase;
    // End of variables declaration//GEN-END:variables
}
